---
#####################################################################
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP.
#####################################################################

- name: Remove key added using Ansible module
  authorized_key:
    user: root
    state: absent
    key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}" 
  when: "{{ item  !=  inventory_hostname }}"
  with_items:
    - "{{ groups[group_names[0]] }}"

- name: Remove the buffer from localhost
  shell: 'rm -rf buffer'
  delegate_to: localhost 

- name: Uncomment line from /etc/ssh/ssh_config
  lineinfile:
    dest: /etc/ssh/ssh_config
    regexp: '^   StrictHostKeyChecking no'
    line: '#   StrictHostKeyChecking ask'
