---
#####################################################################
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP.
#####################################################################


      - name: Check if Serviceguard Storage Flex Add-on software is already installed
        shell: |
            rpm -q --queryformat '%{version}' serviceguard-flex-storage-addon
        register: sglx_storage_flex_result
        changed_when: no
        ignore_errors: true
      
      - name: Skip the node if Serviceguard Storage Flex Add-on software is already installed
        fail:
            msg: "Serviceguard Storage Flex Add-on sofwtare version {{ sglx_storage_flex_result.stdout_lines }} 
                  is already installedi. Use upgrade option in playbook." 
        when: sglx_storage_flex_result.rc == 0
        ignore_errors: true

      - set_fact:
            iso_location: "{{ sglx_add_on_inst_upg_params.storage_flex_add_on.iso_params.iso_location }}"

      - name: Mount the Storage Flex Add-on ISO on the node
        include_tasks: roles/common/tasks/sglx_mount_iso.yml
        vars:
            mount_result:
                rc: 0
                opmsg: "" 
        when: sgver_result.rc != 0
        ignore_errors: true
      
      - set_fact:
            mount_result:
                rc: 1
                opmsg: "Skipping install {{ ansible_hostname }} as Serviceguard is 
                        already installed use upgrade option in playbook"
        when: sgver_result.rc == 0

      - name: Set OS distribution dependent variables
        include_vars: "{{ item }}"
        with_items:
            - group_vars/os_{{ ansible_facts['distribution'] }}.yml

      - name: Install Serviceguard Storage Flex Add-on software
        shell: |
            {{ sglx_cmd_path }}/cminstaller -d {{ mount_dir }}
        register: cminstaller_output
        ignore_errors: true
        when:
            - mount_result.rc == 0
            - sglx_add_on_inst_upg_params.storage_flex_add_on.install_upgrade

      - name: Summarize installation | Success
        debug:
            msg: " Installation of Serviceguard Storage Flex Add-on software is succeeded on node: {{ cminstaller_output.stdout_lines }}"
        when:
            - cminstaller_output.rc == 0
            - sglx_add_on_inst_upg_params.storage_flex_add_on.install_upgrade
        ignore_errors: yes

      - name: Summarize installation | Failure
        debug:
            msg: " Installation of Serviceguard Storage Flex Add-on software is failed on node: \n {{ cminstaller_output.stdout_lines }}"
        when:
            - cminstaller_output.rc != 0
            - sglx_add_on_inst_upg_params.storage_flex_add_on.install_upgrade
        ignore_errors: yes

      - name: Unmount the ISO on the node
        include_tasks: roles/common/tasks/sglx_umount_iso.yml
        vars:
            umount_result:
                rc: 0
                opmsg: "" 
        ignore_errors: true
      
      - debug:
            msg: "Umount of ISO returned with {{ umount_result.rc }} 
                  and {{ umount_result.opmsg }}"  
