---
#####################################################################
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP.
#####################################################################

# ansible vars for sap-nw-hosts
sap_nw_id: "id-1"
