---
#####################################################################
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP.
#####################################################################

oracle_cmd_path: "/opt/cmcluster/conf/scripts/tkit/oracle"
