---
#####################################################################
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP.
#####################################################################

- name: Set OS distribution dependent variables
  include_vars: group_vars/os_{{ ansible_facts['distribution'] }}.yml

- name: Check if Serviceguard is installed
  shell: | 
      rpm -q --queryformat '%{version}' serviceguard
  register: sgver_result
  changed_when: no
  ignore_errors: true

- name: Abort view of cluster when Serviceguard is not installed
  debug:
     msg: "Serviceguard is not installed on node {{ ansible_hostname }}.
           Aborting cluster view!!"
  when: sgver_result.rc != 0 

- meta: end_play
  when: sgver_result.rc != 0 

- name: View Serviceguard cluster 
  run_once: yes
  shell: |
      {{ sglx_cmd_path }}/cmviewcl
  register: cmview_output
    
- debug:
      var: cmview_output.stdout_lines 
  when: cmview_output.rc == 0 
  run_once: yes
