---
#####################################################################
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP.
#####################################################################

# tasks file for install
- debug:
      msg: "Value of variable {{ sglx_inst_upg_mode }}" 

- name: Serviceguard for Linux | Checking iso mode
  include_tasks: iso_install.yml
  when: sglx_inst_upg_mode  == "iso"

- name: Serviceguard for Linux | Checking repo mode
  include_tasks: repo_install.yml
  when: sglx_inst_upg_mode == "repo"
 
